#!/usr/bin/env bash
# Package PetOS into a real, double-clickable macOS .app bundle with the Python
# sidecar vendored inside it, then ad-hoc codesign so launch-at-login works.
#
# Output: app/dist/PetOS.app
# Optional: pass --install to also copy it into /Applications.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_DIR="$ROOT/app"
DIST="$APP_DIR/dist"
APP="$DIST/PetOS.app"
CONTENTS="$APP/Contents"
MACOS="$CONTENTS/MacOS"
RES="$CONTENTS/Resources"
VERSION="0.1.0"
BUNDLE_ID="com.petos.app"

echo "==> Building release binary"
(cd "$APP_DIR" && swift build -c release)
BIN="$APP_DIR/.build/release/PetOS"
[ -x "$BIN" ] || { echo "release binary missing at $BIN"; exit 1; }

echo "==> Assembling bundle at $APP"
rm -rf "$APP"
mkdir -p "$MACOS" "$RES"
cp "$BIN" "$MACOS/PetOS"

# Copy the SwiftPM resource bundle into Resources so Bundle.module (used for the
# header logo) resolves it, and so codesign accepts it as a valid subcomponent.
RESBUNDLE="$APP_DIR/.build/release/PetOS_PetOS.bundle"
[ -d "$RESBUNDLE" ] && cp -R "$RESBUNDLE" "$RES/"

echo "==> Building app icon (.icns)"
LOGO="$APP_DIR/Sources/PetOS/Resources/petos_logo.png"
if [ -f "$LOGO" ]; then
    ICONSET="$DIST/AppIcon.iconset"
    rm -rf "$ICONSET"; mkdir -p "$ICONSET"
    for s in 16 32 64 128 256 512 1024; do
        sips -z $s $s "$LOGO" --out "$ICONSET/icon_${s}x${s}.png" >/dev/null 2>&1 || true
    done
    # retina @2x names
    cp "$ICONSET/icon_32x32.png"   "$ICONSET/icon_16x16@2x.png"   2>/dev/null || true
    cp "$ICONSET/icon_64x64.png"   "$ICONSET/icon_32x32@2x.png"   2>/dev/null || true
    cp "$ICONSET/icon_256x256.png" "$ICONSET/icon_128x128@2x.png" 2>/dev/null || true
    cp "$ICONSET/icon_512x512.png" "$ICONSET/icon_256x256@2x.png" 2>/dev/null || true
    cp "$ICONSET/icon_1024x1024.png" "$ICONSET/icon_512x512@2x.png" 2>/dev/null || true
    iconutil -c icns "$ICONSET" -o "$RES/AppIcon.icns" 2>/dev/null || \
        echo "   (iconutil failed; app runs without a custom icon)"
    rm -rf "$ICONSET"
fi

cat > "$CONTENTS/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>            <string>PetOS</string>
    <key>CFBundleDisplayName</key>     <string>PetOS</string>
    <key>CFBundleIdentifier</key>      <string>${BUNDLE_ID}</string>
    <key>CFBundleExecutable</key>      <string>PetOS</string>
    <key>CFBundleIconFile</key>        <string>AppIcon</string>
    <key>CFBundlePackageType</key>     <string>APPL</string>
    <key>CFBundleVersion</key>         <string>${VERSION}</string>
    <key>CFBundleShortVersionString</key><string>${VERSION}</string>
    <key>LSMinimumSystemVersion</key>  <string>13.0</string>
    <key>NSHighResolutionCapable</key> <true/>
    <key>NSHumanReadableCopyright</key><string>PetOS</string>
</dict>
</plist>
PLIST

echo "==> Vendoring sidecar source"
mkdir -p "$RES/agentd"
cp -R "$ROOT/agentd/src" "$RES/agentd/src"
cp "$ROOT/agentd/pyproject.toml" "$RES/agentd/pyproject.toml"
# Keep generated bytecode out of the signed app bundle. Python may have created
# these during local smoke tests or syntax checks, and codesign seals them.
find "$RES/agentd/src" -type d -name "__pycache__" -prune -exec rm -rf {} +

echo "==> Building relocatable sidecar venv (this can take a minute)"
rm -rf "$RES/agentd-venv"
python3 -m venv --copies "$RES/agentd-venv"
"$RES/agentd-venv/bin/python" -m pip install -q --upgrade pip
"$RES/agentd-venv/bin/python" -m pip install -q \
    fastapi "uvicorn[standard]" httpx "websockets>=12"

echo "==> Ad-hoc codesigning"
# Strip stray xattrs that trip codesign, then deep-sign (inner bundles + the
# vendored python get signed too, so SMAppService accepts the login item).
xattr -cr "$APP" 2>/dev/null || true
if codesign --force --deep --sign - "$APP"; then
    codesign --verify --deep "$APP" 2>&1 | sed 's/^/   /' || true
    echo "   signed OK"
else
    echo "   (codesign failed; app still runs, but launch-at-login won't register)"
fi

echo "==> Done: $APP"

if [ "${1:-}" = "--install" ]; then
    echo "==> Installing to /Applications"
    rm -rf "/Applications/PetOS.app"
    cp -R "$APP" "/Applications/PetOS.app"
    echo "   Installed. Launch: open /Applications/PetOS.app"
fi

echo
echo "Launch with:  open \"$APP\""
echo "The pawprint appears in the menu bar. Login-at-login works once launched."
